all:
  hosts:
    inetRouter:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key