all:
  hosts:
    inetRouter:
      ip4addr: 192.168.255.1/30    
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ip4addr: 192.168.255.2/30    
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
    testServer1:
      vlan_id: 100
      vlan_name: vlan100      
      ip4addr: 10.10.10.254/24    
      ansible_port: 2201
      ansible_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
    testClient1:
      vlan_id: 100
      vlan_name: vlan100      
      ip4addr: 10.10.10.1/24    
      ansible_port: 2202
      ansible_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key
    testServer2:
      vlan_id: 101
      vlan_name: vlan101      
      ip4addr: 10.10.10.254/24        
      ansible_port: 2203
      ansible_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key
    testClient2:
      vlan_id: 101
      vlan_name: vlan101      
      ip4addr: 10.10.10.1/24    
      ansible_port: 2204
      ansible_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
  children:
    Routers:
      hosts:
        inetRouter:
        centralRouter:
    Isolated:
      hosts:
        testServer1:
        testClient1:
        testServer2:
        testClient2:
    
