all:
  hosts:
    inetRouter:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
    testServer1:
      ansible_port: 2201
      ansible_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
    testClient1:
      ansible_port: 2202
      ansible_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key
    testServer2:
      ansible_port: 2203
      ansible_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key
    testClient2:
      ansible_port: 2204
      ansible_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
  children:
    Routers:
      hosts:
        inetRouter:
        centralRouter:
    vlan100:
      hosts:
        testServer1:
        testClient1:
    vlan101:
      hosts:
        testServer2:
        testClient2:
    
