---
- name:  install needed network manager libs
  hosts: all
  become: yes
  vars:
    net_libs: NetworkManager-glib
  tasks:
    - name: install needed network manager libs
      yum:
        name: "{{ net_libs }}"
        state: installed
      with_items:
        - NetworkManager-glib
        - libnm-qt-devel.x86_64
        - nm-connection-editor.x86_64
        - libsemanage-python
        - policycoreutils-python


- name:  Isolated Config| testClients & testServers Network Configuration
  hosts: Isolated
  become: yes
  tasks:
    - name: Try to set vlan&ip 
      shell:
        nmcli con add type vlan con-name "{{  vlan_name  }}"  dev eth1 id "{{  vlan_id  }}" ip4 "{{  ip4addr  }}"     
      tags:
        - set-client-vlan-ip
      notify:
        - reload network interface
        - restart NetworkManager
        - restart Network


  handlers:
    - include: handlers/reload_network_interface.yml
    - include: handlers/restart_network_manager.yml
    - include: handlers/restart_network.yml
    
      
- name:  Routers Config| Routers Network Configuration
  hosts: Routers
  become: yes
  vars:
    team_name: Team0
    nmcli_team:
      - conn_name: "{{ team_name }}"
        ip4: "{{ ip4addr }}"
    nmcli_team_slave:
      - conn_name: Team-Port0
        ifname: eth1
        master: "{{ team_name }}"
      - conn_name: Team-Port1
        ifname: eth2
        master: "{{ team_name }}"
  tasks:
    - name: Add a Team connection with static IP configuration
      nmcli:
        type: team
        mode: balance-alb
        conn_name: '{{ item.conn_name }}'
        ip4: '{{ item.ip4 }}'
        state: present
      with_items:
        - '{{ nmcli_team }}'
        
    - name: Try nmcli add team-slave
      nmcli:
        type: team-slave
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.ifname }}'
        master: '{{ item.master }}'
        state: present
      with_items:
        - '{{ nmcli_team_slave }}'
      tags:
        - add team-slave
      notify:
        - reload network interface
        - restart NetworkManager
        - restart Network


  handlers:
    - include: handlers/reload_network_interface.yml
    - include: handlers/restart_network_manager.yml
    - include: handlers/restart_network.yml


