---
- name:  Configurate hosts
  hosts: pgservers
  become: yes
  vars:
    postgresql_repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    postgresql_packages:
      - postgresql11
      - postgresql11-server
      - postgresql11-contrib
      - python-psycopg2

  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install PostgreSQL repo
      yum:
        name: "{{ postgresql_repo }}"
        state: present

    - name: Install PostgreSQL packages
      package:
        name: "{{ postgresql_packages }}"
        state: present


- name:  Init master
  hosts: master
  become: yes
  vars:
    postgresql_version: "11"
    postgresql_service: postgresql-11
    postgresql_bin_path: "/usr/pgsql-11/bin"
    postgresql_data_dir: "/var/lib/pgsql/11/data/"
    postgresql_config_path: "/var/lib/pgsql/11/data"
    physical_replication_slot: standby_slot

  tasks:
    - name: PostgreSQL database init
      command: "{{ postgresql_bin_path }}/postgresql-11-setup initdb"
      args:
        creates: "{{ postgresql_data_dir }}/PG_VERSION"

    - name: Run PostgreSQL
      systemd:
        name: "{{ postgresql_service }}"
        state: started
        enabled: yes

    - name: Create physical slot for replication if doesn't exist
      become_user: postgres
      postgresql_slot:
        slot_name: "{{ physical_replication_slot }}"
      
  handlers:
    - include: handlers/all.yml

