---
- name:  Configurate hosts
  hosts: pgservers
  become: yes
  vars:
    postgresql_repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install PostgreSQL repo
      yum:
        name: "{{ postgresql_repo }}"
        state: present

    - name: Install PostgreSQL packages
      package:
        name: "{{ postgresql_packages }}"
        state: present
        notify: PostgreSQL service enable
