# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  },
  :backup => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.152'
  }

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            # Подключаем дополнительные диски
            #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
          end

          box.vm.provision "shell", inline: <<-SHELL
             mkdir -p ~root/.ssh
             cp ~vagrant/.ssh/auth* ~root/.ssh
             echo "export LANG=en_US.UTF-8" >> /etc/profile.d/lang.sh
             echo "export LANGUAGE=en_US.UTF-8" >> /etc/profile.d/lang.sh
             echo "export LC_COLLATE=C" >> /etc/profile.d/lang.sh
             echo "export LC_CTYPE=en_US.UTF-8" >> /etc/profile.d/lang.sh
             source /etc/profile.d/lang.sh
          SHELL
#          box.vm.provision "ansible" do |ansible|
#             ansible.playbook = "playbook.yml"
#             ansible.limit = "all"
#          end                                                                                  
          
      end
  end

end

