version: "3"

services:
  web:
    image: stump773/my-nginx-image:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front_end
  phpfpm:
    image: php:fpm-alpine
    volumes:
      - ./www:/var/www/html
    networks:
      - front_end

networks:
  front_end:
