---
- name: Enable PostgreSQL
  systemd:
    name: "{{ postgresql_service }}"

- name: Restart PostgreSQL
  systemd:
    name: "{{ postgresql_service }}"
    state: restarted
    enabled: yes

- name: Reload PostgreSQL
  systemd:
    name: "{{ postgresql_service }}"
    state: reloaded

