all:
  hosts:
    master:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/master/virtualbox/private_key
    slave:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/slave/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
