---
- name:  Configurate hosts
  hosts: all
  become: yes
  tasks:
    - name: Install percona release
      yum:
        name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
        state: present
      tags:
        - install-percona-release

    - name: Install percona server
      yum:
        name: Percona-Server-server-57
        state: present
      tags:
        - install-percona-server
        
    - name: Copy MySQL conf files 
      copy:
        src: conf/conf.d/
        dest: /etc/my.cnf.d/
        owner: root
        group: root
        mode: '0644'

    - name: Start MySQL
      systemd:
        name: mysql
        state: started
        
    - name: Get automate generated mysql password
      shell: grep 'A temporary password is generated' /var/log/mysqld.log | awk '{print $11}' 
      register: current_password
      
    - debug:
        msg:
        - "{{ current_password.stdout_lines }}"
        - "{{ mysql_password }}"
        
    
    - name: Set mysql password
      shell: 
        mysql --connect-expired-password -uroot -p'{{ current_password.stdout }}' -e 'ALTER USER USER() IDENTIFIED BY "{{ mysql_password }}"'
      ignore_errors: yes

    - name: Copy bet.dmp 
      copy:
        src: bet.dmp
        dest: /vagrant
        owner: root
        group: root
        mode: '0644'
      when: role is defined and role == 'master'
