---
- name:  Configurate hosts
  hosts: all
  become: yes
  tasks:
    - name: Install percona release
      yum:
        name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
        state: present
      tags:
        - install-percona-release

    - name: Install percona server
      yum:
        name: Percona-Server-server-57
        state: present
      tags:
        - install-percona-server
        
    - name: Copy MySQL conf files 
      copy:
        src: conf/conf.d/
        dest: /etc/my.cnf.d/
        owner: root
        group: root
        #directory_mode
        mode: '0644'

    - name: Start MySQL
      systemd:
        name: mysql
        state: started
