# -*- mode: ruby -*-
# vim: set ft=ruby :



MACHINES = {
  :otuslinuxhw7 => {
        :box_name => "centos/7",
        
        :ip_addr => '192.168.11.101',

		
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk \
	      redhat-lsb-core \
	      wget \
	      rpmdevtools \
	      rpm-build \
	      createrepo \
	      yum-utils \
	      gcc
	      cd /root
	      wget https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
	      wget https://www.openssl.org/source/latest.tar.gz
	      tar -xvf latest.tar.gz
	      yum-builddep rpmbuild/SPECS/nginx.spec -y
	      #wget -O rpmbuild/SPECS/nginx.spec
	      rpmbuild -bb rpmbuild/SPECS/nginx.spec
	      yum localinstall -y rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
	      systemctl start nginx
	      mkdir /usr/share/nginx/html/repo
	      cp rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm /usr/share/nginx/html/repo/
	      wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm \
	      -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm
	      createrepo /usr/share/nginx/html/repo/
	      #wget -O /etc/nginx/conf.d/default.conf
              nginx -t
              nginx -s reload 	     
	      curl -a http://localhost/repo/
	      cat >> /etc/yum.repos.d/otus.repo << EOF
	      [otus]
	      name=otus-linux
	      baseurl=http://localhost/repo
	      gpgcheck=0
	      enabled=1
	      EOF	      
  
     	  SHELL
      end
  end
end

