# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :rasvpn => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.10',
        :hostname => 'rasvpn',
        :ssh_port => '2201'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.ssh.port = boxconfig[:ssh_port]
      config.vm.network :forwarded_port, guest: 22, host: boxconfig[:ssh_port], id: "ssh", auto_correct: true
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxconfig[:hostname]

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

           box.vm.provision "shell", run: "always", inline: <<-SHELL
            set -x
            yum install -y epel-release
            yum install -y openvpn easy-rsa policycoreutils-python
            semanage port -a -t openvpn_port_t -p udp 1207
            ###########################################################
            #Переходим в директорию /etc/openvpn/ и инициализируем pki#
            ###########################################################
            cd /etc/openvpn/
            echo 'yes' | /usr/share/easy-rsa/3/easyrsa init-pki            
            
            ###########################################################
            #Сгенерируем необходимые ключи и сертификаты длā сервера  #
            ###########################################################
            echo 'rasvpn' | /usr/share/easy-rsa/3/easyrsa build-ca nopass
            echo 'rasvpn' | /usr/share/easy-rsa/3/easyrsa gen-req server nopass
            echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req server server
            /usr/share/easy-rsa/3/easyrsa gen-dh > /dev/null 2>&1
            openvpn --genkey --secret ta.key
                
            echo 'iroute 192.168.10.0 255.255.255.0' > /etc/openvpn/client/client
            
            ######################################
            #Сгенерируем сертификаты для клиента.#
            ######################################
            echo 'client' | /usr/share/easy-rsa/3/easyrsa gen-req client nopass
            echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req client client
            
           SHELL
      end
  end
         
end
