all:
  hosts:
    server:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/server/virtualbox/private_key
    client:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/client/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
    dev: tun
