---
- name:  Configurate hosts for vpn tun test 
  hosts: all
  become: yes
  tasks:
    - name: Install epel-release
      package:
        name:
          - epel-release
        state: present
      tags:
        - epel-installation

    - name: Install needed packages
      package:
        name:
          - openvpn 
          - iperf3 
          - easy-rsa
          - tcpdump
        state: present
      tags:
        - install-packages

    - name: Copy static key 
      template:
        src: templates/static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
      tags:
        - static-key-deploy
    
- name:  Configurate server for vpn tun test 
  hosts: server
  become: yes
  tasks:
    - name: Create openvpn config file from template
      template:
        src: templates/server.conf.j2
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
      notify:
        - restart_openvpn
      tags:
        - openvpn-server-configuration
  handlers:
    - include: handlers/restart_openvpn.yml

- name:  Configurate client for vpn tun test 
  hosts: client
  become: yes
  tasks:
    - name: Create openvpn config file from template
      template:
        src: templates/client.conf.j2
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
      notify:
        - restart_openvpn
      tags:
        - openvpn-client-configuration
  handlers:
    - include: handlers/restart_openvpn.yml
