# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.10',
        :hostname => 'server.loc'
  },
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.20',
        :hostname => 'client.loc'        
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxconfig[:hostname]

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provision "shell", inline: <<-SHELL
            #yum -y install tcpdump epel-release openvpn iperf3 easy-rsa
            setenforce 0
          SHELL

      end
  end
end
