# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.10',
        :hostname => 'server.loc'
  },
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.20',
        :hostname => 'client.loc'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxconfig[:hostname]

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
      end
  end
 
  config.vm.provision :ansible do |ansible|
     ansible.playbook = "playbook.yml"
  end

end
